### ISSUE TITLE
NPE in ServiceValidator when loading TriMet feed

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-lib#105]
NPE thrown [here](https://github.com/conveyal/gtfs-lib/blob/6285437423b8a988f0303b803e4a3c10eef8e6a9/src/main/java/com/conveyal/gtfs/validator/ServiceValidator.java#L81) when loading TriMet feed:
```
java.lang.NullPointerException
	at com.conveyal.gtfs.validator.ServiceValidator.validateTrip(ServiceValidator.java:81)
	at com.conveyal.gtfs.validator.NewTripTimesValidator.processTrip(NewTripTimesValidator.java:173)
	at com.conveyal.gtfs.validator.NewTripTimesValidator.validate(NewTripTimesValidator.java:74)
	at com.conveyal.gtfs.loader.Feed.validate(Feed.java:101)
	at com.conveyal.gtfs.GTFS.validate(GTFS.java:85)
	at com.conveyal.datatools.manager.models.FeedVersion.validate(FeedVersion.java:323)
	at com.conveyal.datatools.manager.jobs.ValidateFeedJob.jobLogic(ValidateFeedJob.java:32)
	at com.conveyal.datatools.common.status.MonitorableJob.run(MonitorableJob.java:118)
	at com.conveyal.datatools.common.status.MonitorableJob.run(MonitorableJob.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The TriMet feed only uses `calendar_dates.txt`, so it appears that there is an issue when adding trip durations to the `ServiceInfo` object for feeds that don't have standard service calendars.

**Comment by landonreed** [comment]
This was due to a `trip.route_id` that was a bad reference so the route was null.  I'm adding a check for null route here.

**Comment by landonreed** [comment]
I realize now that GitHub would have closed this issue automatically once the fix was merged to master, but it appears now that it may not perform the same behavior because I closed manually.  I am going to close manually once and for all.
