### ISSUE TITLE
NPE on getTripsPerDateOfService

### ISSUE THREAD

**Issue by demory** [conveyal/gtfs-lib#14]
This error appears when validating the second most recent version of the Centro feed on the 511NY data manager:

```
java.lang.NullPointerException
        at com.conveyal.gtfs.validator.service.impl.FeedStats.getTripsPerDateOfService(FeedStats.java:163)
        at com.conveyal.datatools.manager.models.FeedVersion.validate(FeedVersion.java:238)
        at com.conveyal.datatools.manager.controllers.api.FeedVersionController.getValidationResult(FeedVersionController.java:237)
        at com.conveyal.datatools.manager.controllers.api.FeedVersionController$$Lambda$48/902919927.handle(Unknown Source)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by landonreed** [comment]
Also having issues replicating this @demory.  Is this the feed version you're using: `Centro_20160223T155210-05_63dcf8a5-b2c6-470e-849f-36b72022af16.zip`?

**Comment by landonreed** [comment]
closed.
