### ISSUE TITLE
NPE on getCalendarServiceRangeStart

### ISSUE THREAD

**Issue by demory** [conveyal/gtfs-lib#16]
Occurs when validating any version of Bronx Bus

```
java.lang.NullPointerException
	at com.conveyal.gtfs.validator.service.impl.FeedStats.getCalendarServiceRangeStart(FeedStats.java:65)
	at com.conveyal.datatools.manager.models.FeedVersion.validate(FeedVersion.java:211)
	at com.conveyal.datatools.manager.controllers.api.DumpController.validateAll(DumpController.java:110)
```

**Comment by landonreed** [comment]
closed.
