### ISSUE TITLE
DateTimeParseException in getCalendarServiceRangeStart 

### ISSUE THREAD

**Issue by demory** [conveyal/gtfs-lib#17]
Occurs when validating the latest version of the CARTS feed in 511NY

```
java.time.format.DateTimeParseException: Text '0' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDate.parse(LocalDate.java:400)
	at com.conveyal.gtfs.validator.service.impl.FeedStats.getCalendarServiceRangeStart(FeedStats.java:70)
	at com.conveyal.datatools.manager.models.FeedVersion.validate(FeedVersion.java:211)
```

**Comment by landonreed** [comment]
@demory, I can't seem to recreate this.  Are you using this version: `CARTS_20150609T174716-04_74eb8a63-c7bd-4ea0-8361-e58c87acd7d7.zip`?

**Comment by mattwigway** [comment]
If there is a date in the feed that is in fact specified as 0 (or more likely, is missing and Java is kindly defaulting integers to 0) this could happen I think.

**Comment by landonreed** [comment]
I think this ended up being fixed either directly or indirectly through some other fix.
