### ISSUE TITLE
JsonMappingException - Can not resolve PropertyFilter with id 'bbox'

### ISSUE THREAD

**Issue by barbeau** [conveyal/gtfs-lib#46]
If I use this GTFS data:
http://gohart.org/google/google_transit.zip

...and run this command (using current master branch at fb2eb615f509efd1b0f57a8760a35b9eb795c6c2):

` java -jar target/gtfs-lib-2.2.0-SNAPSHOT-shaded.jar -validate google_transit.zip result.json`

I get this exception:

~~~
$ java -jar target/gtfs-lib-2.2.0-SNAPSHOT-shaded.jar -validate google_transit.zip result.json
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Table feed_info was missing but it is not required.
[main] INFO com.conveyal.gtfs.GTFSFeed - Feed ID is undefined, pester maintainers to include a feed ID. Using file name google_transit.
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table agency from agency.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar from calendar.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar_dates from calendar_dates.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table fare_attributes from fare_attributes.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table fare_rules from fare_rules.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table routes from routes.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table shapes from shapes.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table stops from stops.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Table transfers was missing but it is not required.
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table trips from trips.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Table frequencies was missing but it is not required.
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table stop_times from stop_times.txt
[main] INFO com.conveyal.gtfs.GTFSFeed - 0 errors
[main] INFO com.conveyal.gtfs.GTFSFeed - Building stop to stop times index
[main] INFO com.conveyal.gtfs.GTFSFeed - Building trips per service index
[main] INFO com.conveyal.gtfs.GTFSFeed - Building services per date index
[main] INFO com.conveyal.gtfs.GTFSFeed - Generating unique names for patterns
[main] INFO com.conveyal.gtfs.GTFSFeed - Total patterns: 140
[main] INFO com.conveyal.gtfs.GTFSFeed - DuplicateStopsValidator finished in 1894 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - HopSpeedsReasonableValidator finished in 0 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - MisplacedStopValidator finished in 247 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - NamesValidator finished in 13 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - OverlappingTripsValidator finished in 204 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - ReversedTripsValidator finished in 514 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - TripTimesValidator finished in 391 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - UnusedStopValidator finished in 5 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - 8 validators completed in 3269 milliseconds.
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not resolve PropertyFilter with id 'bbox'; no FilterProvider configured (through reference chain: com.conveyal.gtfs.validator.model.ValidationResult["feedStatistics"]->com.conveyal.gtfs.stats.model.FeedStatistic["bounds"])
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.findPropertyFilter(StdSerializer.java:274)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFieldsFiltered(BeanSerializerBase.java:683)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:150)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:809)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:684)
        at com.conveyal.gtfs.util.json.JsonManager.writePretty(JsonManager.java:73)
        at com.conveyal.gtfs.GTFSMain.main(GTFSMain.java:47)
~~~

**Comment by barbeau** [comment]
I think this is a similar issue to https://github.com/conveyal/gtfs-validator/issues/17 - https://github.com/conveyal/gtfs-validator/commit/944730de4aae24a589dd46e220bbe176c172eee3 may fix this.

**Comment by barbeau** [comment]
I believe I have a fix for this, will open PR shortly.

**Comment by barbeau** [comment]
PR open at https://github.com/conveyal/gtfs-lib/pull/47.
