### ISSUE TITLE
NPE when loading Champagne feed

### ISSUE THREAD

**Issue by abyrd** [conveyal/gtfs-lib#63]
```
22:44:13.885 [Thread-14] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table agency from agency.txt
22:44:13.889 [Thread-14] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar from calendar.txt
22:44:13.904 [Thread-14] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar_dates from calendar_dates.txt
22:44:13.938 [Thread-14] INFO  c.conveyal.gtfs.model.Entity$Loader - Table fare_attributes was missing but it is not required.
22:44:13.938 [Thread-14] INFO  c.conveyal.gtfs.model.Entity$Loader - Table fare_rules was missing but it is not required.
22:44:13.939 [Thread-14] INFO  c.conveyal.gtfs.model.Entity$Loader - Loading GTFS table routes from routes.txt
Exception in thread "Thread-14" java.lang.RuntimeException: java.lang.NullPointerException
        at com.conveyal.taui.controllers.BundleController.lambda$null$1(BundleController.java:126)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.conveyal.taui.controllers.BundleController.lambda$create$5(BundleController.java:129)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.conveyal.gtfs.model.Route$Loader.loadOneRow(Route.java:67)
        at com.conveyal.gtfs.model.Entity$Loader.loadTable(Entity.java:267)
        at com.conveyal.gtfs.GTFSFeed.loadFromFile(GTFSFeed.java:192)
        at com.conveyal.gtfs.GTFSFeed.loadFromFile(GTFSFeed.java:229)
        at com.conveyal.gtfs.GTFSCache.put(GTFSCache.java:95)
        at com.conveyal.gtfs.GTFSCache.put(GTFSCache.java:79)
        at com.conveyal.gtfs.api.ApiMain.registerFeedSource(ApiMain.java:100)
        at com.conveyal.taui.controllers.BundleController.lambda$null$1(BundleController.java:121)
        ... 9 more
```

**Comment by abyrd** [comment]
This is a duplicate of #40 which is already solved, but in version 2.x of gtfs-lib which is not reverse-compatible with old MapDBs. Therefore analysis and r5 have never made it past v1.3. So I made a feature branch for gtfs-lib 1.3.x and released 1.3.1 and updated those other projects to use 1.3.1.
