### ISSUE TITLE
Crashes when reading GTFS with bad stop references

### ISSUE THREAD

**Issue by abyrd** [conveyal/gtfs-lib#96]
This is probably caused by a feed that has stop_times referencing stops that don't exist (I've seen that locally). It makes Analysis unable to load the feed, and it just fails silently from the user point of view.

```
22:15:47.402 [Thread-12] INFO  com.conveyal.gtfs.GTFSFeed - Generating unique names for patterns
22:15:47.407 [Thread-12] INFO  c.conveyal.taui.persistence.MongoMap - Bundle CH Merge 3 (fixed dates) (5a77849a896fd02b831a4bd0) CH Merge 3 (fixed dates) updated by abyrd+sbb@conveyal.com (sbb)
Exception in thread "Thread-12" com.conveyal.taui.AnalysisServerException
	at com.conveyal.taui.AnalysisServerException.Unknown(AnalysisServerException.java:77)
	at com.conveyal.taui.controllers.BundleController.lambda$null$1(BundleController.java:143)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.conveyal.taui.controllers.BundleController.lambda$create$5(BundleController.java:146)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abyrd** [comment]
It appears that this code may be entirely removed in current gtfs-lib. We might have to go looking elsewhere for problems like this that mostly just require null checks.
